# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20160916_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='image',
            field=models.ImageField(default='treasure_images/default.png', upload_to='treasure_images/'),
        ),
    ]
